markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: JL's Melody
description: Tech, idea, thinking, coding, finding...
keywords: Melody, Coding, Tech, Idea
url: http://blog.kkiiiu.com
feed: /atom.xml
favicon: https://avatars0.githubusercontent.com/u/1155563?v=2&u=3dc6b3da64adb810998124b3164333eba9a1d3cb&s=140

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: JL
    email: kkiiiu@gmail.com
    imageLink: http://www.gravatar.com/avatar/92a3834ea57e2b9f21033f5a19654ee3.png
    simpleIntro: 
      <p>Coder, Liver, Dreamer...</p>
      <p>To be or not to be, it's not a problem.</p>
    detailIntro:
      <p>Nothing...</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-github-alt
    url: http://github.com/johnny-lv
  - class: icon-weibo
    url: http://weibo.com/vliilv
  #- class: icon-twitter
   # url: http://twitter.com/vliNilv

#Links
customLinks:
  - item:
    - text: Tim's Blog
      url: http://www.timtang.me
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends

#googleAnaly, your id link UA-12345678-X
#googleAnaly:
  #config: true
  #id: UA-40169250-1

#comment config
disqus:
  config: true
  id: kkiiiu

duoshuo:
  config: false
  id: kkiiiu
